import { Injectable } from '@angular/core';
import { Places } from '../models/places';

@Injectable({
  providedIn: 'root'
})
export class CountryDataService {

  constructor() { }
  

  places:Places[]  = [
    {
      key: "bangalore",
      place : "Bangalore",
      country : "Bangalore, Karnataka, India",
      image : "/assets/gotours/imgs/city/bangalore.jpg",
      description : "Nestled in the heart of Karnataka, Bangalore, also known as Bengaluru, is a city of contrasts, blending technological prowess with cultural richness. With Dream Adventures Services as your travel companion, your journey to Bangalore promises a seamless blend of innovation, history, and artistic exploration.",
      description1 : "Cubbon Park: Green Oasis Begin your exploration at Cubbon Park, a lush green oasis in the city center. The park offers serene walking trails, landscaped gardens, and a respite from urban life.",
      description2 : "Lalbagh Botanical Garden: Horticultural Haven Visit Lalbagh Botanical Garden, home to a stunning collection of exotic plants and a glasshouse inspired by London’s Crystal Palace.",
      description3 : "Vidhana Soudha: Architectural Marvel Explore Vidhana Soudha, the seat of Karnataka’s legislature and a prime example of Neo-Dravidian architecture. Its grandeur is captivating.",
      withus : "At Dream Adventures Services, we understand the dynamic spirit of Bangalore and its diverse cultural heritage. Our experienced travel specialists craft personalized itineraries that ensure your Bangalore journey is filled with tech insights, cultural experiences, and artistic exploration. Whether you’re a tech enthusiast, a history buff, or an art lover, we tailor your experience to match your passions.",
    },
    {
      key: "hyderabad",
      place : "Hyderabad",
      country : "Hyderabad, Andhra, India",
      image : "/assets/gotours/imgs/city/hyderabad.jpg",
      description : "Nestled in the heart of Telangana, Hyderabad is a city of mesmerizing contrasts, blending its rich Nizami heritage with cutting-edge technology. With Dream Adventures Services as your travel companion, your journey to Hyderabad promises a seamless blend of history, innovation, and culinary delights.",
      description1 : "Charminar: Icon of Hyderabad Begin your exploration at the iconic Charminar, a centuries-old monument that stands as a symbol of the city. Climb to the top for panoramic views of the bustling streets.",
      description2 : "Golconda Fort: Majestic Citadel Visit Golconda Fort, a historic citadel known for its acoustics and grandeur. Explore the fort’s impressive architecture and learn about its history.",
      description3 : "Hyderabadi Cuisine: Culinary Delights Indulge in the flavors of Hyderabadi cuisine. Savor biryani, haleem, and kebabs at local eateries and experience the city’s rich culinary heritage.",
      withus : "At Dream Adventures Services, we understand the allure of Hyderabad’s Nizami splendor and its contributions to the tech world. Our experienced travel specialists craft personalized itineraries that ensure your Hyderabad journey is filled with historical insights, technological marvels, and gastronomic delights. Whether you’re a history enthusiast, a tech geek, or a food connoisseur, we tailor your experience to match your passions.",
    },
    {
      key: "mysore",
      place : "Mysore",
      country : "Mysore, Karnataka, India",
      image : "/assets/gotours/imgs/city/mysore.jpg",
      description : "Nestled in the heart of Karnataka, Mysore is a city that exudes royal grandeur, rich heritage, and a timeless charm. With Dream Adventures Services as your travel companion, your journey to Mysore promises a seamless blend of regal palaces, cultural immersion, and traditional craftsmanship.",
      description1 : "Mysore Palace: Royal Splendor Begin your exploration at the Mysore Palace, a magnificent royal residence that dazzles with its Indo-Saracenic architecture, intricate artwork, and opulent interiors.",
      description2 : "Chamundi Hill: Spiritual Ascent Visit Chamundi Hill and its sacred temple dedicated to Goddess Chamundeshwari. The climb offers panoramic views of Mysore and its surrounding landscape.",
      description3 : "Silk and Crafts: Artistic Treasures Explore Mysore’s bustling markets known for exquisite silk sarees, sandalwood products, and traditional handicrafts. Witness the city’s artistic heritage.",
      withus : "At Dream Adventures Services, we understand the regal allure of Mysore and its cultural richness. Our experienced travel specialists craft personalized itineraries that ensure your Mysore journey is filled with historical insights, spiritual experiences, and artistic discoveries. Whether you’re a history enthusiast, a spiritual seeker, or an art lover, we tailor your experience to match your passions.",
    },
    {
      key : "dubai",
      place : "Dubai",
      country : "Dubai, UAE",
      image : "/assets/gotours/imgs/city/dubai.jpg",
      description : "Nestled on the shores of the Arabian Gulf, Dubai is a dazzling city that seamlessly blends futuristic architecture, luxurious living, and the timeless beauty of the desert. With Dream Adventures Services as your travel companion, your journey to Dubai promises an extravagant mix of skyscrapers, golden sands, and cultural richness.",
      description1 : "Burj Khalifa: Touch the Sky Begin your exploration at the Burj Khalifa, the world’s tallest building. Take an elevator ride to the observation deck for panoramic views of the city.",
      description2 : "Desert Safari: Sand Dunes and Starlit Nights Experience the magic of the desert with a desert safari. Ride over sand dunes, savor a traditional Bedouin meal, and witness the starlit beauty of the desert night.",
      description3 : "Dubai Mall: Retail Wonderland Visit the Dubai Mall, a shopper’s paradise with luxury boutiques, an indoor ice rink, and the mesmerizing Dubai Fountain show.",
      withus : "At Dream Adventures Services, we understand the allure of Dubai’s modern marvels and desert allure. Our expert travel planners craft tailor-made itineraries to ensure your Dubai journey is filled with architectural wonders, desert adventures, and cultural encounters. Whether you’re a shopper, an adventurer, or a lover of luxury, we curate experiences that match your desires.",
    },
    {
      key : "london",
      place : "London",
      country : "London, UK",
      image : "/assets/gotours/imgs/city/london.jpg",
      description : "Nestled on the banks of the River Thames, London is a city that seamlessly blends centuries-old tradition with modern vibrancy. With Dream Adventures Services as your travel companion, your journey to London promises an exciting mix of historic landmarks, cultural diversity, and contemporary excitement.",
      description1 : "The British Museum: Timeless Treasures Begin your exploration at The British Museum, home to a vast collection of art and artifacts from around the world, including the Rosetta Stone and the Elgin Marbles.",
      description2 : "Westminster Abbey: Royal Heritage Visit Westminster Abbey, where British monarchs have been crowned and historic events celebrated. Marvel at its stunning Gothic architecture.",
      description3 : "West End Theatres: Theatrical Excellence Experience the magic of London’s West End theaters. Attend a world-class play or musical in the theater district.",
      withus : "At Dream Adventures Services, we understand the allure of London’s historical treasures and contemporary energy. Our expert travel planners craft tailor-made itineraries to ensure your London journey is filled with cultural enrichment, royal heritage, and cosmopolitan experiences. Whether you’re a history buff, a theater enthusiast, or a foodie, we curate experiences that match your desires.",
    },
    {
      key : "malaysia",
      place : "Malaysia",
      country : "Malaysia",
      image : "/assets/gotours/imgs/city/malaysia.jpg",
      description : "Located in Southeast Asia, Malaysia is a nation that boasts stunning natural landscapes, a rich tapestry of cultures, and vibrant modern cities. With Dream Adventures Services as your travel guide, your journey to Malaysia promises an enriching blend of tropical adventures, cultural exploration, and culinary delights.",
      description1 : "Kuala Lumpur: Urban Elegance Begin your exploration in Kuala Lumpur, Malaysia’s capital, and visit the iconic Petronas Twin Towers, explore Batu Caves, and stroll through the bustling streets of Chinatown.",
      description2 : "Langkawi: Island Paradise Visit Langkawi, a tropical paradise of pristine beaches and lush rainforests. Experience the Langkawi Sky Bridge and take a boat tour of the mangroves.",
      description3 : "Penang: Culinary Haven Explore Penang, known as the food capital of Malaysia. Savor delicious street food, visit George Town’s historic streets, and discover vibrant street art.",
      withus : "At Dream Adventures Services, we understand the allure of Malaysia’s natural beauty and cultural diversity. Our expert travel planners craft tailor-made itineraries to ensure your Malaysian journey is filled with natural wonders, cultural encounters, and gastronomic delights. Whether you’re an adventurer, a culture enthusiast, or a food connoisseur, we curate experiences that match your desires.",
    },
    {
      key : "paris",
      place : "Paris",
      country : "Paris, France",
      image : "/assets/gotours/imgs/city/paris.jpg",
      description : "Nestled in the heart of France, Paris is a city that epitomizes romance, art, and timeless elegance. With Dream Adventures Services as your travel guide, your journey to Paris promises a captivating blend of iconic landmarks, artistic treasures, and gourmet delights.",
      description1 : "Eiffel Tower: Iconic Landmark Begin your exploration at the Eiffel Tower, where you can ascend to the top for breathtaking views of the city and the Seine River.",
      description2 : "Louvre Museum: Artistic Marvels Explore the Louvre Museum, home to masterpieces like the Mona Lisa, the Venus de Milo, and the Winged Victory of Samothrace.",
      description3 : "Montmartre: Bohemian Spirit Visit Montmartre, the historic artistic neighborhood, and discover the charming streets, the Basilica of the Sacré-Cœur, and the Moulin Rouge cabaret.",
      withus : "At Dream Adventures Services, we understand the allure of Paris’s romantic ambiance and artistic heritage. Our expert travel planners craft tailor-made itineraries to ensure your Parisian journey is filled with cultural enrichment, romantic moments, and gourmet experiences. Whether you’re a lover of art, a hopeless romantic, or a culinary enthusiast, we curate experiences that match your desires.",
    },
    {
      key : "chandigarh",
      place : "Chandigarh",
      country : "Chandigarh, India",
      image : "/assets/gotours/imgs/city/chandigarh.jpg",
      description : "Nestled at the foothills of the Shivalik Range, Chandigarh stands as a testament to urban planning brilliance and the harmonious coexistence of modernity and nature. Designed by renowned architect Le Corbusier, this city is a unique blend of innovation, green spaces, and cultural vibrancy.",
      description1 : "One of Chandigarh’s most iconic attractions is the Rock Garden, a mesmerizing creation by artist Nek Chand. Built entirely from discarded materials and industrial waste, this open-air sculpture garden is a testament to human creativity and the transformative power of art. Intricate pathways lead you through a labyrinth of sculptures, waterfalls, and dreamlike installations.",
      description2 : "Escape the urban hustle at Sukhna Lake, a serene reservoir that offers respite from the city’s fast pace. The shimmering waters, surrounded by lush greenery, provide the perfect setting for a leisurely stroll, boat ride, or a quiet moment of reflection. The lake’s tranquility is a stark contrast to the vibrant cityscape.",
      description3 : "The Capitol Complex, another masterpiece by Le Corbusier, is a symbol of Chandigarh’s architectural excellence. It comprises three iconic structures: the Secretariat, the High Court, and the Legislative Assembly. The geometric design and open spaces emphasize the city’s commitment to modern urban living.",
      withus : "At Fala International Services, we understand that each traveler is unique. Our seasoned travel experts craft personalized itineraries that suit your preferences, allowing you to make the most of your Chandigarh adventure. Whether you’re a nature enthusiast, an adventure seeker, or a cultural explorer, we have the perfect plan for you.",
    },
    {
      key : "dalhousie",
      place : "Dalhousie",
      country : "Dalhousie, India",
      image : "/assets/gotours/imgs/city/dalhousie.jpg",
      description : "Nestled in the lap of the Dhauladhar Range, Dalhousie is a serene hill station that beckons you to escape the chaos and embrace the calming embrace of nature. With Fala International Services as your travel companion, your journey to Dalhousie promises to be a seamless blend of comfort and discovery.",
      description1 : "Khajjiar: The Mini Switzerland of India Begin your exploration at Khajjiar, often referred to as the “Mini Switzerland of India.” The lush meadows, dense forests, and a tranquil lake make it an enchanting getaway. With Fala International Services, your itinerary is curated to ensure you make the most of this picturesque gem.",
      description2 : "Panchpula: Nature’s Refreshment Visit Panchpula, where glistening waterfalls and cascading streams create a soothing ambiance. Allow the cool breeze and the sound of nature’s symphony to rejuvenate your senses. Our travel experts ensure your journey is a harmonious blend of natural wonders and serenity.",
      description3 : "Chamera Lake: Tranquil Retreat Indulge in the tranquility of Chamera Lake, a serene reservoir surrounded by mountains. Whether you’re seeking relaxation or seeking adventure through water sports, Fala International Services tailors your experience to match your desires.",
      withus : "At Fala International Services, we understand that each traveler is unique. Our seasoned travel experts craft personalized itineraries that suit your preferences, allowing you to make the most of your Dalhousie adventure. Whether you’re a nature enthusiast, an adventure seeker, or a cultural explorer, we have the perfect plan for you.",
    },
    {
      key : "dharamshala",
      place : "Dharamshala",
      country : "Dharamshala, India",
      image : "/assets/gotours/imgs/city/dharamshala.jpg",
      description : "Nestled in the lap of the Himalayas, Dharamshala is a serene retreat that invites you to immerse yourself in spirituality and breathtaking landscapes. With Fala International Services by your side, your journey to Dharamshala is a seamless blend of cultural exploration and rejuvenation.",
      description1 : "Namgyal Monastery: Embrace Spiritual Serenity Begin your Dharamshala journey at the Namgyal Monastery, a spiritual haven for Buddhists. The tranquil ambiance and the sound of prayer wheels create an atmosphere of profound peace. With Fala International Services, your itinerary is designed to ensure you connect with the spiritual essence of this serene destination.",
      description2 : "Triund Trek: A Hiker’s Paradise Embark on the Triund Trek, a moderate hike that rewards you with panoramic vistas of the Dhauladhar Range. Our travel experts ensure your trekking experience is safe and enjoyable, allowing you to soak in the beauty of the Himalayan foothills.",
      description3 : "Dalai Lama Temple: Seek Blessings Visit the Dalai Lama Temple Complex, where you can seek blessings and immerse yourself in Tibetan culture. The tranquility of the temple and the surrounding landscape create a meditative ambiance that soothes the soul.",
      withus : "At Fala International Services, we believe that every journey should be as unique as the traveler. Our experienced travel specialists curate personalized itineraries that cater to your interests and preferences. Whether you’re a nature enthusiast, a spiritual seeker, or an adventure lover, we tailor your Dharamshala experience to match your desires.",
    },
    {
      key : "dwarka",
      place : "Dwarka",
      country : "Dwarka, India",
      image : "/assets/gotours/imgs/city/dwarka.jpg",
      description : "Dwarka, an ancient city on the shores of the Arabian Sea, beckons with its profound spiritual significance and historical treasures. With Fala International Services as your travel companion, your journey to Dwarka is a seamless fusion of devotion and exploration.",
      description1 : "Dwarkadhish Temple: The Sacred Heart Begin your journey at the revered Dwarkadhish Temple, dedicated to Lord Krishna. The temple’s majestic spire and intricate carvings stand as a testament to devotion. With Fala International Services, your itinerary is designed to ensure a soul-enriching experience at this spiritual haven.",
      description2 : "Nageshwar Jyotirlinga: A Divine Encounter Visit the Nageshwar Jyotirlinga, one of the 12 sacred shrines dedicated to Lord Shiva. The temple’s serene ambiance and spiritual energy offer a unique opportunity for introspection and connection. Our travel experts ensure your visit is seamless and spiritually uplifting.",
      description3 : "Rukmini Devi Temple: A Tale of Love Explore the Rukmini Devi Temple, known for its architectural beauty and the legends of love it encapsulates. The temple’s intricate sculptures and vibrant surroundings create a captivating ambiance that transports you to a bygone era.",
      withus : "At Fala International Services, we understand the importance of a spiritually enriching journey. Our experienced travel specialists craft customized itineraries that allow you to immerse yourself in the essence of Dwarka’s spirituality. Whether you seek inner peace, cultural insight, or historical exploration, we tailor your experience to match your desires.",
    },
    {
      key : "gurugram",
      place : "Gurugram",
      country : "Gurugram, India",
      image : "/assets/gotours/imgs/city/gurugram.jpg",
      description : "Gurugram, a bustling metropolis in Haryana, welcomes you with its modernity, business vibrancy, and dynamic lifestyle. With Fala International Services as your travel partner, your journey to Gurugram combines comfort, convenience, and discovery.",
      description1 : "Cyber Hub: Epicenter of Entertainment Begin your exploration at Cyber Hub, a modern oasis that entices with its myriad dining options, entertainment venues, and vibrant atmosphere. With Fala International Services, your itinerary is crafted to ensure you experience the cosmopolitan essence of Gurugram.",
      description2 : "Kingdom of Dreams: Immerse in Culture Visit the Kingdom of Dreams, a cultural hub that offers a captivating blend of theatrical performances, art, and cuisine. The larger-than-life shows and immersive experiences make it a must-visit destination for art enthusiasts.",
      description3 : "DLF Cyber City: Business and Beyond Explore DLF Cyber City, the corporate hub that epitomizes Gurugram’s economic prowess. The sleek skyscrapers, luxurious malls, and upscale restaurants form the heart of the city’s commercial landscape.",
      withus : "At Fala International Services, we recognize the importance of a seamless urban experience. Our experienced travel specialists curate personalized itineraries that showcase the best of Gurugram’s modernity, ensuring you have a comfortable and enriching stay.",
    },
    {
      key : "haridwar",
      place : "Haridwar",
      country : "Haridwar, India",
      image : "/assets/gotours/imgs/city/haridwar.jpg",
      description : "Nestled along the banks of the sacred Ganges River, Haridwar beckons with its spiritual aura and ancient rituals. With Fala International Services as your travel partner, your journey to Haridwar becomes a seamless blend of devotion, culture, and tranquility.",
      description1 : "Har Ki Pauri: The Holy Ghat Begin your journey at Har Ki Pauri, the revered bathing ghat where the Ganges washes away sins. Witness the mesmerizing Ganga Aarti, a divine spectacle of lamps and chants that captures the essence of spiritual reverence. With Fala International Services, your itinerary ensures you experience this ritual in all its glory.",
      description2 : "Mansa Devi Temple: Blessings Await Visit the Mansa Devi Temple, perched atop the Bilwa Parvat hill. The temple is dedicated to Goddess Mansa Devi, believed to fulfill devotees’ wishes. Our travel experts ensure your visit is a spiritually uplifting experience, allowing you to seek blessings with peace and devotion.",
      description3 : "Chandi Devi Temple: A Hilltop Journey Embark on a cable car ride to the Chandi Devi Temple, situated on the Neel Parvat hill. The panoramic views of Haridwar and the serene temple setting offer a serene retreat for introspection and worship.",
      withus : "At Fala International Services, we understand the significance of a spiritually enriched journey. Our experienced travel specialists craft personalized itineraries that resonate with your spiritual aspirations. Whether you seek blessings, cultural insights, or serene moments by the Ganges, we tailor your Haridwar experience to match your desires.",
    },
    {
      key : "jim-corbet",
      place : "Jim-corbet",
      country : "Jim-corbet, India",
      image : "/assets/gotours/imgs/city/jim-corbet.jpg",
      description : "Nestled in the heart of the lush Himalayan foothills, Jim Corbett National Park invites you to experience the untamed beauty of nature. With Fala International Services as your travel companion, your journey to Jim Corbett promises a seamless blend of adventure, wildlife, and serenity.",
      description1 : "Safari Adventures: Encounter the Wild Embark on thrilling safaris through the dense jungles of Jim Corbett National Park. With Fala International Services, your safari experience is carefully curated to maximize your chances of spotting majestic tigers, elusive leopards, and a diverse array of wildlife.",
      description2 : "Dhikala Forest Lodge: Amidst Nature’s Bounty Stay at the Dhikala Forest Lodge, nestled amidst the wilderness of the park. Wake up to the symphony of birds and the rustling of leaves, surrounded by the untamed beauty that Jim Corbett offers.",
      description3 : "Garjiya Devi Temple: Blend of Nature and Spirituality Visit the Garjiya Devi Temple, perched on a rocky hill amidst the Kosi River. The temple’s panoramic views and serene atmosphere provide a unique blend of nature’s splendor and spiritual devotion.",
      withus : "At Fala International Services, we understand the allure of nature’s mysteries. Our experienced travel specialists curate personalized itineraries that offer an immersive wildlife experience. Whether you’re a nature enthusiast, an adventure seeker, or a wildlife photographer, we tailor your Jim Corbett journey to match your passions.",
    },
    {
      key : "katra",
      place : "Katra",
      country : "Katra, India",
      image : "/assets/gotours/imgs/city/katra.jpg",
      description : "Nestled in the lap of the Trikuta Mountains, Katra beckons with its spiritual aura and natural beauty. With Fala International Services as your travel companion, your journey to Katra becomes a seamless blend of devotion, adventure, and serenity.",
      description1 : "Vaishno Devi Shrine: The Sacred Trek Embark on the sacred trek to the Vaishno Devi Shrine, a revered pilgrimage site dedicated to Goddess Vaishno Devi. The journey offers not only spiritual fulfillment but also the thrill of conquering nature’s challenges. With Fala International Services, your pilgrimage is meticulously planned for a safe and meaningful experience.",
      description2 : "Ardhkuwari: Caves of Blessings Visit Ardhkuwari, a cave temple en route to the Vaishno Devi Shrine. The cave’s spiritual ambiance and the legend of the goddess’ halfway stop create a unique setting for reflection and devotion.",
      description3 : "Ban Ganga: Serene Waterside Relax by the Ban Ganga River, where pilgrims often take a dip before beginning their sacred trek. The tranquil surroundings and the flowing waters offer a serene escape from the bustling world.",
      withus : "At Fala International Services, we understand the significance of a pilgrimage’s spiritual impact. Our experienced travel specialists craft personalized itineraries that ensure your journey to Katra is both seamless and spiritually enriching. Whether you seek blessings, inner peace, or a sense of accomplishment, we tailor your experience to match your desires.",
    },
    {
      key : "kufri",
      place : "Kufri",
      country : "Kufri, India",
      image : "/assets/gotours/imgs/city/kufri.jpg",
      description : "Nestled in the lap of the Himalayas, Kufri beckons with its snow-covered landscapes and thrilling escapades. With Fala International Services as your travel partner, your journey to Kufri promises a seamless blend of adventure, beauty, and winter magic.",
      description1 : "Skiing and Snowboarding: Thrills on the Slopes Embark on thrilling skiing and snowboarding adventures on Kufri’s snow-covered slopes. With Fala International Services, your winter sports experience is carefully tailored to suit your skill level, ensuring an exhilarating yet safe adventure.",
      description2 : "Himalayan Nature Park: Explore the Wilderness Visit the Himalayan Nature Park, home to diverse Himalayan wildlife including snow leopards and red pandas. The park’s serene trails and pristine landscapes offer a unique opportunity to connect with nature’s beauty.",
      description3 : "Mahasu Peak: Panoramic Vistas Conquer Mahasu Peak, the highest point in Kufri, for breathtaking panoramic views of the surrounding mountains. The exhilarating trek and the stunning vista make it a must-visit destination for nature enthusiasts.",
      withus : "At Fala International Services, we understand the allure of winter adventures. Our experienced travel specialists curate personalized itineraries that ensure your Kufri journey is filled with snow-packed excitement and cozy moments. Whether you’re a seasoned skier, an adventure lover, or a nature admirer, we tailor your experience to match your passions.",
    },
    {
      key : "landsowne",
      place : "Landsowne",
      country : "Landsowne, India",
      image : "/assets/gotours/imgs/city/landsowne.jpg",
      description : "Nestled amidst the Garhwal Himalayas, Lansdowne invites you to experience tranquility and natural beauty. With Fala International Services as your travel companion, your journey to Lansdowne promises a seamless blend of relaxation, exploration, and mountain charm.",
      description1 : "Bhulla Lake: Reflections of Peace Begin your journey at Bhulla Lake, a serene oasis surrounded by pine trees. The lake’s calm waters and picturesque setting offer a tranquil escape for nature lovers. With Fala International Services, your experience is designed for a rejuvenating retreat.",
      description2 : "Tarkeshwar Mahadev Temple: Spirituality Amidst Nature Visit the Tarkeshwar Mahadev Temple, where devotion and nature converge. The temple’s lush surroundings and the mystical aura of Lord Shiva create a sacred ambiance for seekers and explorers alike.",
      description3 : "Tip N Top Point: Panoramic Vistas Explore Tip N Top Point, a vantage point that offers breathtaking panoramic views of the Himalayas. The cool breeze and the sweeping vista make it a perfect spot for relaxation and reflection.",
      withus : "At Fala International Services, we recognize the allure of mountain retreats. Our experienced travel specialists curate personalized itineraries that ensure your Lansdowne journey is a harmonious blend of serenity and exploration. Whether you seek solitude, natural beauty, or a cultural escape, we tailor your experience to match your desires.",
    },
    {
      key : "lehladhak",
      place : "Lehladhak",
      country : "Lehladhak, India",
      image : "/assets/gotours/imgs/city/lehladhak.jpg",
      description : "Nestled in the high mountains of northern India, Leh Ladakh is a land of stark contrasts and breathtaking beauty. With Fala International Services as your travel companion, your journey to Leh Ladakh promises a seamless blend of adventure, culture, and tranquility.",
      description1 : "Nubra Valley: The Desert in the Sky Begin your exploration at Nubra Valley, a high-altitude desert known for its dramatic landscapes and the enchanting Bactrian camels. With Fala International Services, your itinerary is designed to ensure you soak in the surreal beauty of this unique destination.",
      description2 : "Pangong Lake: A Shimmering Jewel Visit the mesmerizing Pangong Lake, where the azure waters stretch to meet the horizon. The lake’s serene ambiance and changing hues throughout the day offer a tranquil escape from the world.",
      description3 : "Leh Palace: A Glimpse into History Explore the Leh Palace, a historic royal residence that provides panoramic views of the city and the surrounding mountains. The palace’s architecture and artifacts offer insights into Ladakh’s rich heritage.",
      withus : "At Fala International Services, we understand the allure of Himalayan adventures. Our experienced travel specialists craft personalized itineraries that ensure your Leh Ladakh journey is filled with excitement and cultural exploration. Whether you’re an adventurer, a history enthusiast, or a nature lover, we tailor your experience to match your passions.",
    },
    {
      key : "manali",
      place : "Manali",
      country : "Manali, India",
      image : "/assets/gotours/imgs/city/manali.jpg",
      description : "Nestled in the lap of the Himalayas, Manali is a paradise for nature lovers, adventure seekers, and those seeking a serene escape. With Fala International Services as your travel companion, your journey to Manali promises a seamless blend of adventure, culture, and relaxation.",
      description1 : "Rohtang Pass: The Gateway to Adventure Begin your exploration at Rohtang Pass, a high mountain pass that offers thrilling activities like snow sports and breathtaking views of the surrounding peaks. With Fala International Services, your adventure at Rohtang Pass is carefully planned for an unforgettable experience.",
      description2 : "Solang Valley: Thrills in the Mountains Visit Solang Valley, an adventure hub where you can enjoy activities like paragliding, zorbing, and trekking. The valley’s natural beauty and adrenaline-pumping adventures make it a must-visit destination.",
      description3 : "Hidimba Devi Temple: A Spiritual Retreat Explore the Hidimba Devi Temple, a wooden temple dedicated to the goddess Hidimba. The temple’s unique architecture and tranquil surroundings offer a peaceful escape from the world.",
      withus : "At Fala International Services, we understand the allure of the Himalayas. Our experienced travel specialists craft personalized itineraries that ensure your Manali journey is filled with adventure and relaxation. Whether you’re a thrill-seeker, a nature enthusiast, or a cultural explorer, we tailor your experience to match your passions.",
    },
    {
      key : "mussoorie",
      place : "Mussoorie",
      country : "Mussoorie, India",
      image : "/assets/gotours/imgs/city/mussoorie.jpg",
      description : "Where Nature's Charms Embrace You with Fala International Services. Nestled in the Garhwal Himalayas, Mussoorie is a picturesque hill station that invites you to bask in its natural beauty and colonial charm. With Fala International Services as your travel companion, your journey to Mussoorie promises a seamless blend of relaxation, exploration, and rejuvenation.",
      description1 : "Kempty Falls: A Refreshing Retreat Begin your exploration at Kempty Falls, a cascading wonder amidst lush greenery. The falls provide a refreshing escape and a chance to dip your toes in its cool waters. With Fala International Services, your visit to Kempty Falls is part of a rejuvenating journey.",
      description2 : "Camel’s Back Road: Stroll Amidst Nature Walk along Camel’s Back Road, a serene trail that offers stunning views of the Himalayas. The road’s unique shape and the breathtaking sunset views make it a delightful experience.",
      description3 : "Gun Hill: Panoramic Vistas Visit Gun Hill, the second-highest point in Mussoorie, for panoramic views of the Doon Valley and the surrounding peaks. The cool breeze and the stunning vista create an ideal spot for relaxation.",
      withus : "At Fala International Services, we understand the allure of hill stations. Our experienced travel specialists craft personalized itineraries that ensure your Mussoorie journey is filled with scenic beauty and cultural exploration. Whether you’re a nature enthusiast, a history buff, or a leisure traveler, we tailor your experience to match your passions.",
    },
    {
      key : "nainital",
      place : "Nainital",
      country : "Nainital, India",
      image : "/assets/gotours/imgs/city/nainital.jpg",
      description : "Nestled in the Kumaon region of the Himalayas, Nainital is a gem of a hill station renowned for its serene lakes and lush landscapes. With Fala International Services as your travel companion, your journey to Nainital promises a seamless blend of relaxation, exploration, and tranquillity.",
      description1 : "Naini Lake: A Mirror of Nature Begin your exploration at Naini Lake, the heart and soul of Nainital. The pristine waters mirror the surrounding hills and offer opportunities for boating and lakeside walks. With Fala International Services, your experience at Naini Lake is part of a tranquil journey.",
      description2 : "Naina Devi Temple: A Sacred Pause Visit the Naina Devi Temple, perched on the northern shore of Naini Lake. The temple’s spiritual aura and the panoramic views it provides create a serene ambiance for devotion and reflection.",
      description3 : "The Mall Road: Stroll and Shop Explore The Mall Road, a bustling street lined with shops, cafes, and boutiques. It’s the perfect place to indulge in local cuisine and shop for souvenirs.",
      withus : "At Fala International Services, we understand the allure of lakeside retreats. Our experienced travel specialists craft personalized itineraries that ensure your Nainital journey is filled with scenic beauty and cultural exploration. Whether you’re a nature lover, a spiritual seeker, or a leisure traveler, we tailor your experience to match your passions.",
    },
    {
      key : "rishikesh",
      place : "Rishikesh",
      country : "Rishikesh, India",
      image : "/assets/gotours/imgs/city/rishikesh.jpg",
      description : "Nestled in the lap of the Himalayas and straddling the sacred Ganges River, Rishikesh is a spiritual haven that invites you to seek inner peace and adventure. With Fala International Services as your travel companion, your journey to Rishikesh promises a seamless blend of spirituality, yoga, and nature's serenity.",
      description1 : "Triveni Ghat: The Confluence of Souls Begin your spiritual journey at Triveni Ghat, where the Ganges, Yamuna, and Saraswati rivers merge. Witness the soul-soothing Ganga Aarti as the riverbanks come alive with chants and lamps. With Fala International Services, your experience at Triveni Ghat is part of a profound spiritual exploration.",
      description2 : "Laxman Jhula and Ram Jhula: Suspension Bridges of Devotion Visit the iconic Laxman Jhula and Ram Jhula, suspension bridges that span the Ganges. These bridges are not only architectural marvels but also revered pilgrimage sites.",
      description3 : "Yoga Retreats: Inner Harmony Immerse yourself in the art of yoga and meditation at one of Rishikesh’s renowned ashrams and yoga retreats. The tranquil surroundings and experienced instructors create the perfect environment for inner exploration.",
      withus : "At Fala International Services, we understand the significance of a spiritually enriched journey. Our experienced travel specialists craft personalized itineraries that ensure your Rishikesh experience is filled with inner peace and cultural insights. Whether you seek spiritual growth, holistic wellness, or a connection with nature, we tailor your experience to match your desires.",
    },
    {
      key : "shimla",
      place : "Shimla",
      country : "Shimla, India",
      image : "/assets/gotours/imgs/city/shimla.jpg",
      description : "Nestled in the Shivalik range of the Himalayas, Shimla, the 'Queen of Hill Stations,' invites you to step back in time and savor its colonial heritage and natural splendor. With Fala International Services as your travel companion, your journey to Shimla promises a seamless blend of history, culture, and mountain charm.",
      description1 : "The Ridge: Stroll Amidst Heritage Begin your exploration at The Ridge, a historic open space that offers panoramic views of the surrounding mountains. The colonial architecture and cultural events make it a delightful experience. With Fala International Services, your visit to The Ridge is part of a journey through time.",
      description2 : "Mall Road: Shopping and Savories Explore Mall Road, Shimla’s bustling street lined with shops, cafes, and heritage buildings. It’s the perfect place to savor local cuisine and shop for souvenirs.",
      description3 : "Jakhu Temple: Seek Blessings Visit Jakhu Temple, dedicated to Lord Hanuman and perched atop Jakhu Hill. The temple’s serene surroundings and the giant Hanuman statue create a spiritual ambiance for seekers and explorers alike.",
      withus : "At Fala International Services, we understand the allure of colonial charm. Our experienced travel specialists craft personalized itineraries that ensure your Shimla journey is filled with history, culture, and natural beauty. Whether you’re a history buff, a food enthusiast, or a leisure traveler, we tailor your experience to match your passions.",
    },
    {
      key : "srinagar",
      place : "Srinagar",
      country : "Srinagar, India",
      image : "/assets/gotours/imgs/city/srinagar.jpg",
      description : "Nestled in the heart of the Kashmir Valley, Srinagar is often referred to as 'Paradise on Earth' for its breathtaking natural beauty and serene landscapes. With Fala International Services as your travel companion, your journey to Srinagar promises a seamless blend of beauty, culture, and tranquility.",
      description1 : "Dal Lake: A Water Wonderland Begin your exploration on Dal Lake, where shikara rides take you through a world of floating gardens and traditional houseboats. The serene waters and the view of the surrounding mountains create a magical experience. With Fala International Services, your time on Dal Lake is part of a journey into Kashmir’s enchantment.",
      description2 : "Mughal Gardens: A Floral Symphony Visit the Mughal Gardens, a testament to Kashmir’s rich heritage and love for gardens. The meticulously designed terraced lawns, flowing fountains, and fragrant blooms offer a sensory delight.",
      description3 : "Shankaracharya Temple: Spiritual Solace Explore the Shankaracharya Temple, perched atop a hill, providing panoramic views of Srinagar. The temple’s spiritual ambiance and historical significance create a serene escape for seekers.",
      withus : "At Fala International Services, we understand the allure of Kashmir’s beauty. Our experienced travel specialists craft personalized itineraries that ensure your Srinagar journey is filled with natural wonders, cultural exploration, and tranquility. Whether you’re a nature lover, a history enthusiast, or a leisure traveler, we tailor your experience to match your passions.",
    },
    {
      key : "varanasi",
      place : "Varanasi",
      country : "Varanasi, India",
      image : "/assets/gotours/imgs/city/varanasi.jpg",
      description : "Nestled on the banks of the sacred Ganges River, Varanasi, also known as Kashi, is a city that beckons with its spiritual aura and ancient traditions. With Fala International Services as your travel companion, your journey to Varanasi promises a seamless blend of spirituality, culture, and reverence.",
      description1 : "Ganges Ghats: A Spiritual Odyssey Begin your exploration at the Ganges Ghats, where ancient rituals and ceremonies unfold every day. Witness the Ganga Aarti at Dashashwamedh Ghat as priests offer prayers to the holy river. With Fala International Services, your spiritual experience along the ghats is part of a profound journey.",
      description2 : "Kashi Vishwanath Temple: Spiritual Center Visit the Kashi Vishwanath Temple, one of the most revered Hindu temples dedicated to Lord Shiva. The temple’s historical significance and spiritual ambiance create a sacred atmosphere for seekers.",
      description3 : "Sarnath: A Place of Enlightenment Explore Sarnath, where Lord Buddha delivered his first sermon. The ancient ruins and the serene gardens offer a glimpse into Buddhism’s rich history and teachings.",
      withus : "At Fala International Services, we understand the importance of a spiritually enriching journey. Our experienced travel specialists craft personalized itineraries that ensure your Varanasi experience is filled with reverence, cultural insights, and inner peace. Whether you’re a spiritual seeker, a history enthusiast, or a cultural explorer, we tailor your experience to match your passions.",
    },
    {
      key : "vrindavan",
      place : "Vrindavan",
      country : "Vrindavan, India",
      image : "/assets/gotours/imgs/city/vrindavan.jpg",
      description : "Nestled on the banks of the sacred Yamuna River, Vrindavan is a town steeped in devotion and the eternal love of Lord Krishna. With Fala International Services as your travel companion, your journey to Vrindavan promises a seamless blend of spirituality, culture, and devotion.",
      description1 : "Banke Bihari Temple: The Divine Encounter Begin your exploration at the Banke Bihari Temple, where devotees seek the divine blessings of Lord Krishna. The temple’s spiritual aura and the soul-stirring bhajans create a sacred atmosphere.",
      description2 : "Radha Raman Temple: A Symbol of Devotion Visit the Radha Raman Temple, dedicated to Lord Krishna’s divine love for Radha. The temple’s intricate architecture and the stories of devotion are a testament to the enduring love story of Radha and Krishna.",
      description3 : "Yamuna Ghats: Spiritual Cleansing Experience the serenity of the Yamuna Ghats, where devotees gather for ritual baths and prayers. The ghats offer a peaceful space for reflection and devotion.",
      withus : "At Fala International Services, we understand the significance of a spiritual journey filled with devotion. Our experienced travel specialists craft personalized itineraries that ensure your Vrindavan experience is filled with reverence, cultural insights, and a deep connection to divine love. Whether you’re a spiritual seeker, a devotee, or a cultural explorer, we tailor your experience to match your passions.",
    },
    {
      key : "darjeeling",
      place : "Darjeeling",
      country : "Darjeeling, India",
      image : "/assets/gotours/imgs/city/darjeeling.jpg",
      description : "Nestled in the lap of the Eastern Himalayas, Darjeeling is a hill station that beckons with its tea gardens, breathtaking vistas, and charming ambiance. With Fala International Services as your travel companion, your journey to Darjeeling promises a seamless blend of natural beauty, culture, and tranquility.",
      description1 : "Tea Gardens: A Sip of Serenity Visit the famous tea gardens of Darjeeling, where you can witness the tea-making process and savor a cup of world-renowned Darjeeling tea.",
      description2 : "Peace Pagoda: Spiritual Serenity Explore the Peace Pagoda, a symbol of peace and harmony. The pagoda’s tranquil surroundings and panoramic views create a serene ambiance for reflection.",
      description3 : "Tiger Hill: Sunrise Splendor Begin your exploration at Tiger Hill, where the first rays of the sun paint the Kanchenjunga range in hues of gold. The sunrise view from here is truly spectacular.",
      withus : "At Fala International Services, we understand the allure of the Himalayas. Our experienced travel specialists craft personalized itineraries that ensure your Darjeeling journey is filled with tea-sipping moments, cultural insights, and natural wonders. Whether you’re a nature enthusiast, a tea connoisseur, or a leisure traveler, we tailor your experience to match your passions.",
    },  
    {
      key : "gangtok",
      place : "Gangtok",
      country : "Gangtok, India",
      image : "/assets/gotours/imgs/city/gangtok.jpg",
      description : "Nestled in the lap of the Eastern Himalayas, Gangtok is the capital city of Sikkim, known for its pristine landscapes, monasteries, and tranquil ambiance. With Fala International Services as your travel companion, your journey to Gangtok promises a seamless blend of natural beauty, spirituality, and cultural richness.",
      description1 : "Tsomgo Lake: A Crystal Oasis Begin your exploration at Tsomgo Lake, a high-altitude glacial lake that reflects the surrounding mountains like a pristine mirror. The crystal-clear waters and the serene surroundings create a mesmerizing experience.",
      description2 : "Enchey Monastery: Spiritual Solace Visit the Enchey Monastery, a sacred Buddhist site known for its serene ambiance and stunning architecture. The monastery offers a peaceful escape from the world.",
      description3 : "Nathula Pass: A Journey to the Border Explore Nathula Pass, a historic trade route and border crossing to China. The breathtaking views of snow-capped peaks and the experience of standing at the Indo-China border are truly remarkable.",
      withus : "At Fala International Services, we understand the allure of the Himalayas. Our experienced travel specialists craft personalized itineraries that ensure your Gangtok journey is filled with spiritual serenity, natural wonders, and cultural exploration. Whether you’re a nature lover, a spiritual seeker, or a cultural enthusiast, we tailor your experience to match your passions.",
    },
    {
      key : "kolkata",
      place : "Kolkata",
      country : "Kolkata, India",
      image : "/assets/gotours/imgs/city/kolkata.jpg",
      description : "Nestled along the banks of the Hooghly River, Kolkata, also known as the 'City of Joy,' is a vibrant metropolis with a rich tapestry of history, culture, and intellectual heritage. With Fala International Services as your travel companion, your journey to Kolkata promises a seamless blend of cultural exploration, culinary delights, and historical revelations.",
      description1 : "Victoria Memorial: A Symbol of Elegance Begin your exploration at the iconic Victoria Memorial, an architectural marvel that stands as a testament to Kolkata’s colonial past. The museum inside offers a glimpse into the city’s history.",
      description2 : "Howrah Bridge: A Lifeline Visit the Howrah Bridge, an engineering wonder that connects Kolkata with Howrah. The bridge’s imposing presence and the bustling activity along the Hooghly River are a sight to behold.",
      description3 : "Dakshineswar Kali Temple: A Spiritual Sojourn Explore the Dakshineswar Kali Temple, dedicated to Goddess Kali. The temple’s serene ambiance and the adjacent Vivekananda Bridge create a spiritual atmosphere for seekers.",
      withus : "At Fala International Services, we understand the richness of Kolkata’s culture. Our experienced travel specialists craft personalized itineraries that ensure your Kolkata journey is filled with cultural experiences, culinary delights, and historical insights. Whether you’re a history enthusiast, a foodie, or a cultural explorer, we tailor your experience to match your passions.",
    },
    {
      key : "puri",
      place : "Puri",
      country : "Puri, India",
      image : "/assets/gotours/imgs/city/puri.jpg",
      description : "Nestled on the eastern coast of India, Puri is a city known for its pristine beaches, vibrant festivals, and deep spiritual significance. With Fala International Services as your travel companion, your journey to Puri promises a seamless blend of devotion, beachside relaxation, and cultural immersion.",
      description1 : "Jagannath Temple: A Divine Center Begin your exploration at the Jagannath Temple, one of the Char Dham pilgrimage sites. The temple is dedicated to Lord Jagannath and hosts the famous Rath Yatra festival. The spiritual energy here is palpable.",
      description2 : "Golden Beach: Tranquil Seaside Visit the Golden Beach, where golden sands meet the azure waters of the Bay of Bengal. The beach offers a serene escape and a chance to witness beautiful sunrises and sunsets.",
      description3 : "Konark Sun Temple: Architectural Marvel Explore the Konark Sun Temple, a UNESCO World Heritage Site known for its intricate architecture and rich history. The temple’s design represents the chariot of the Sun God.",
      withus : "At Fala International Services, we understand the importance of a spiritual journey by the sea. Our experienced travel specialists craft personalized itineraries that ensure your Puri journey is filled with devotion, beachside serenity, and cultural exploration. Whether you’re a spiritual seeker, a beach lover, or a cultural enthusiast, we tailor your experience to match your passions.",
    },
    // {
    //   key : "ahmedabad",
    //   place : "Ahmedabad",
    //   country : "Ahmedabad, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "goa",
    //   place : "Goa",
    //   country : "Goa, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "jaipur",
    //   place : "Jaipur",
    //   country : "Jaipur, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "jodhpur",
    //   place : "Jodhpur",
    //   country : "Jodhpur, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "mount-abu",
    //   place : "Mount-abu",
    //   country : "Mount-abu, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "neemrana",
    //   place : "Neemrana",
    //   country : "Neemrana, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "ranthambore",
    //   place : "Ranthambore",
    //   country : "Ranthambore, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "somnath",
    //   place : "Somnath",
    //   country : "Somnath, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "surat",
    //   place : "Surat",
    //   country : "Surat, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "udaipur",
    //   place : "Udaipur",
    //   country : "Udaipur, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "vadodara",
    //   place : "Vadodara",
    //   country : "Vadodara, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "alleppey",
    //   place : "Alleppey",
    //   country : "Alleppey, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "chennai",
    //   place : "Chennai",
    //   country : "Chennai, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "cochin-kochi",
    //   place : "Cochin-kochi",
    //   country : "Cochin-kochi, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "kovalam",
    //   place : "Kovalam",
    //   country : "Kovalam, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "kumarakom",
    //   place : "Kumarakom",
    //   country : "Kumarakom, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "munnar",
    //   place : "Munnar",
    //   country : "Munnar, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "ooty",
    //   place : "Ooty",
    //   country : "Ooty, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "pondicherry",
    //   place : "Pondicherry",
    //   country : "Pondicherry, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "thekkady",
    //   place : "Thekkady",
    //   country : "Thekkady, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "visakhapatnam",
    //   place : "Visakhapatnam",
    //   country : "Visakhapatnam, India",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "amsterdam",
    //   place : "Amsterdam",
    //   country : "Amsterdam",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "australia",
    //   place : "Australia",
    //   country : "Australia",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "austria",
    //   place : "Austria",
    //   country : "Austria",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "bali",
    //   place : "Bali",
    //   country : "Bali",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "bangkok",
    //   place : "Bangkok",
    //   country : "Bangkok",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "bhutan",
    //   place : "Bhutan",
    //   country : "Bhutan",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "canada",
    //   place : "Canada",
    //   country : "Canada",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "china",
    //   place : "China",
    //   country : "China",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "greece",
    //   place : "Greece",
    //   country : "Greece",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "hong-kong",
    //   place : "Hong-kong",
    //   country : "Hong-kong",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "italy",
    //   place : "Italy",
    //   country : "Italy",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "macau",
    //   place : "Macau",
    //   country : "Macau",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
    // {
    //   key : "new-zealand",
    //   place : "New-zealand",
    //   country : "New-zealand",
    //   image : "",
    //   description : "",
    //   description1 : "",
    //   description2 : "",
    //   description3 : "",
    //   withus : "",
    // },
  ];

  
  getPlaceByKey(key: string): Places | null {
    const place = this.places.find(place => place.key === key);
    return place ? place : null;
  }
  
  getPlaceByPlace(key: string): Places | null {
    const place = this.places.find(place => place.place === key);
    return place ? place : null;
  }
}
